export const STORY_SEEDS = [
  'El colectivo arranca, mirás por la ventana y ves a un pingüino saludándote con sombrero …',
  'Te despertás y la alarma te dice: “Hoy no, quedate en la cama”, pero …',
  'Estás en el ascensor, se corta la luz, y alguien canta un cumpleaños feliz …',
  'Estás comprando pan, y el panadero te entrega un sobre misterioso …',
  'Te sentás en el cine y la pantalla proyecta fotos tuyas de vacaciones …',
  'Un dron aterriza frente a tu ventana y te entrega un paquete extraño …',
  'La música del bar cambia repentinamente a sonidos de granja, y en ese momento …',
  'El mozo te trae un plato que nunca pediste, con una nota escondida debajo …',
  'Estás paseando por la playa y una ola deja un celular en tus pies …',
  'En el parque, un niño te ofrece venderte acciones de su “empresa de helados” …',
  '<1> iba caminando por la calle de noche, pensando en sus cosas, cuando a lo lejos mira a <2> en ropa interior corriendo a toda velocidad...',
  'Estás en una librería, y un libro se cae solo abierto en una página con tu nombre …',
  'Vas a sacar una foto, pero la cámara captura algo que no estaba ahí …',
  'Te subís al taxi y el chofer te pregunta si traés el mapa del tesoro …',
  'Estás en el estadio y la pantalla gigante te enfoca, justo cuando …',
  '<1> iba caminando por la calle de noche, pensando en sus cosas, cuando a lo lejos vio a <2> en ropa interior corriendo a toda velocidad …',
  'En la cancha, la hinchada empezó a cantar “olé, olé, olé, <1>” justo cuando <2> entraba con una pizza gigante …',
  '<1> entró al bondi y el chofer le dijo: “Saldo insuficiente, pero si me das un abrazo de <2> te dejo pasar” …',
  'Mientras <1> cebaba un mate, <2> apareció con una docena de churros y un megáfono anunciando la merienda …',
  'En el kiosco, <1> pidió un alfajor y el kiosquero le entregó un póster autografiado por <2> …',
  '<1> abrió la heladera y encontró a <2> tomando gaseosa directo de la botella …',
  'El semáforo estaba en rojo, <1> esperaba tranquilo, cuando <2> pasó en monociclo disfrazado de gaucho …',
  '<1> fue a cargar la SUBE, pero la máquina mostró la cara de <2> diciendo: “Saldo insuficiente, capo” …',
  'En la verdulería, <1> pidió bananas y el cajón se movió solo hasta mostrar a <2> escondido adentro …',
  '<1> entró al aula, y en el pizarrón gigante decía: “Clase dictada por <2> y <3>” …',
  'Durante el asado, <1> quiso dar vuelta la carne, pero <2> ya estaba sentado como juez con una planilla …',
  'En la fila del banco, el cajero automático empezó a imprimir selfies de <1> y <2> en la playa …',
  '<1> prendió la tele y había un noticiero transmitiendo a <2> bailando cumbia en vivo …',
  'En plena lluvia, <1> abrió el paraguas y adentro estaba <2> tomando mate …',
  'En el subte, <1> vio que la publicidad decía “Se busca a <2> para un casting de telenovela” …',
  '<1> iba en bici por la costanera cuando <2> lo pasó corriendo con una bandera argentina …',
  'En la plaza, las palomas rodearon a <1> mientras <2> les daba órdenes con un silbato …',
  'En el supermercado, <1> escaneó la tarjeta y en la pantalla apareció <2> cantando un tango …',
  'Durante la misa, <1> abrió el misal y encontró la foto de <2> vestido de arquero …',
  '<1> estaba en el colectivo cuando sonó el altavoz: “Próxima parada: casa de <2>” …',
  'En la oficina, la impresora empezó a sacar hojas con dibujos de <1> hechos por <2> …',
  'El semáforo cambió a azul y <1> escuchó la voz de <2> diciendo: “Dale, pasá” …',
  '<1> estaba en el cine, y el tráiler mostraba la historia de <2> como superhéroe …',
  'Mientras <1> esperaba el tren, un perro con chaleco inspector se acercó y le pidió boleto a <2> …',
  'En el boliche, las luces se apagaron y de repente apareció <1> en la cabina de DJ con <2> …',
  '<1> estaba en la panadería y el panadero ofrecía “la docena mágica hecha por <2>” …',
  'Cuando <1> abrió su celular, encontró un grupo nuevo llamado “Cumple de <2> y <3>” …',
  '<1> fue a pagar la cuenta del bar y en el ticket decía “Descuento especial para amigos de <2>” …',
  'En el partido de truco, <1> cantó envido y <2> salió de abajo de la mesa con las cartas ganadoras …',
  'En el colectivo, <1> escuchó la voz del GPS del chofer diciendo: “Atención, <2> está bajando en la próxima” …',
  'Durante el picnic, <1> abrió la canasta y adentro estaba <2> con una guitarra …',
  'En el hospital, el médico le entregó a <1> una receta firmada por <2> en crayones …',
  '<1> quiso prender la compu, pero en la pantalla aparecía la cara de <2> diciendo: “¿Arrancamos?” …',
  'En el shopping, <1> vio un maniquí que de repente se parecía mucho a <2> …',
  'Durante la tormenta, <1> escuchó un trueno que sonaba exactamente como la risa de <2> …',
  'En el casamiento, el cura preguntó si alguien se oponía y apareció <1> con <2> trayendo choripanes …',
  '<1> entró al baño del bar y en el espejo estaba escrita una declaración de amor firmada por <2> …',
  'Cuando <1> abrió la mochila, encontró una nota que decía: “Prestada por <2>, devolvela limpia” …',
  'En la parada de bondi, <1> se dio vuelta y vio que <2> manejaba el colectivo disfrazado …',
  'Durante el recreo, <1> escuchó a los árboles coreando el nombre de <2> …',
  'En el recital, el cantante frenó la canción para felicitar a <1> por venir con <2> …',
  'Mientras <1> tomaba mate, la bombilla empezó a cantar con la voz de <2> …',
  'En el gimnasio, <1> levantaba pesas, pero era <2> quien contaba las repeticiones …',
  '<1> fue a hacerse un tatuaje y el diseño ya estaba listo: la cara de <2> comiendo pizza …',
  'En la cancha de barrio, la pelota rodó sola hasta <1> mientras <2> gritaba gol …',
  'Cuando <1> quiso dormir, la almohada le susurró la receta de empanadas de <2> …',
  'En la parrilla, el parrillero gritó: “¡Se viene el asado de <1> y <2>!” …',
  '<1> bajó del taxi y el chofer le dio como vuelto una foto firmada por <2> …',
  'Durante el carnaval, <1> descubrió que la murga tenía como director a <2> …',
  '<1> entró a la facultad y en la cartelera gigante estaba el dibujo de <2> con bigotes falsos …',
  'En la esquina de su casa, <1> vio a <2> vendiendo entradas para un recital secreto de <3> …',
  'Un desconocido en la calle te entrega una llave sin decir palabra …',
  'Vas a comprar facturas y la panadera te pregunta si querés llevar “el paquete misterioso de medialunas” …',
  'El bondi frena de golpe y el chofer te dice: “Acá bajan los campeones del mundo”, y en ese momento …',
  'Estás haciendo la fila del súper y el de adelante paga con figuritas del Mundial …',
  'El semáforo se pone en rojo y un tipo con camiseta de Boca te pregunta si tenés fuego …',
  'En la cancha, la hinchada empieza a cantar tu nombre aunque vos nunca jugaste …',
  'Estás en la verdulería y el cajón de papas se mueve solo mientras el verdulero silba …',
  'Vas al chino de la esquina y la máquina registradora te devuelve caramelos media hora …',
  'En el kiosco pedís un alfajor y el kiosquero te ofrece “el que cumple deseos” …',
  'Estás en la cola del banco y el de seguridad saca una guitarra y arranca un chamamé …',
  'La radio anuncia: “Atención, hoy se suspenden todos los lunes en Argentina”, y justo …',
  'Te sentás a tomar mate en la plaza y una paloma te pide un sorbo …',
  'En la esquina, un parrillero te ofrece un choripán “con final sorpresa” …',
  'Pedís delivery de empanadas y el repartidor te da un sobre cerrado además de la caja …',
  'Estás en la panadería y una docena de churros se autoproclama tu hinchada personal …',
  'Caminás por Corrientes y un cartel luminoso empieza a mostrar tus tuits viejos …',
];