export const STORY_SEEDS = [
  'Vas caminando solo por la calle y escuchás pasos detrás tuyo, cuando de repente …',
  'Estás en la fila del banco y el cajero te guiña un ojo, y en ese momento …',
  'Abrís la heladera para buscar agua, pero encontrás un control remoto que empieza a sonar …',
  'Tu perro te trae una carta sellada con cera roja, y cuando la abrís …',
  'El profesor escribe en el pizarrón, pero la tiza empieza a contar chistes sola …',
  'El colectivo arranca, mirás por la ventana y ves a un pingüino saludándote con sombrero …',
  'Tu celular vibra y aparece un nuevo chat titulado “Vecinos del Espacio Exterior”, y en ese instante …',
  'Estás cenando tranquilo, cuando tu plato principal te susurra que quiere negociar …',
  'Te despertás y la alarma te dice: “Hoy no, quedate en la cama”, pero …',
  'Entras a la plaza y ves un grupo de ardillas haciendo yoga, justo cuando …',
  'Estás en el gimnasio, y la pesa que levantás empieza a aplaudirte …',
  'Tu gato sube al teclado, escribe algo y lo manda por mail, y en ese momento …',
  'Estás en el ascensor, se corta la luz, y alguien canta un cumpleaños feliz …',
  'La radio anuncia tu nombre como ganador de un premio, pero vos nunca participaste …',
  'Sacás la basura y la bolsa se pone a discutir contigo sobre reciclaje …',
  'Estás comprando pan, y el panadero te entrega un sobre misterioso …',
  'Te sentás en el cine y la pantalla proyecta fotos tuyas de vacaciones …',
  'En medio de la clase online, la cámara muestra a alguien que no sos vos …',
  'Cuando abrís la puerta del baño, adentro hay un grupo ensayando teatro …',
  'Caminás por la vereda y un semáforo te pide la hora …',
  'Estás en el supermercado, y el carrito empieza a dirigirse solo hacia la salida …',
  'Un dron aterriza frente a tu ventana y te entrega un paquete extraño …',
  'Estás lavando los platos, cuando el detergente empieza a dar instrucciones …',
  'Tu computadora abre un juego nuevo sola, y el personaje se parece demasiado a vos …',
  'Tomás el colectivo equivocado, pero adentro todos te llaman por tu nombre …',
  'La música del bar cambia repentinamente a sonidos de granja, y en ese momento …',
  'El mozo te trae un plato que nunca pediste, con una nota escondida debajo …',
  'Estás paseando por la playa y una ola deja un celular en tus pies …',
  'Tu reloj marca una hora inexistente, y cuando mirás de nuevo …',
  'Estás por pagar, pero tu tarjeta dice en voz alta: “Saldo insuficiente, buena suerte” …',
  'Un vecino golpea tu puerta y te pide prestado “un dragón pequeño” …',
  'El cajero automático te devuelve caramelos en lugar de billetes …',
  'Estás jugando a las cartas y una carta nueva aparece sola en tu mano …',
  'Vas al médico y en la sala de espera todos están disfrazados igual que vos …',
  'En medio de la lluvia, un paraguas gigante te sigue por la calle …',
  'Tu café de la mañana trae un mensaje en la espuma, y al leerlo …',
  'En el parque, un niño te ofrece venderte acciones de su “empresa de helados” …',
  '<1> iba caminando por la calle de noche, pensando en sus cosas, cuando a lo lejos mira a <2> en ropa interior corriendo a toda velocidad...',
  'Tu bicicleta arranca sola y te invita a subir con bocinazos …',
  'Abrís la heladera, y un tomate rueda hacia vos como si quisiera hablar …',
  'Estás en una librería, y un libro se cae solo abierto en una página con tu nombre …',
  'Vas a sacar una foto, pero la cámara captura algo que no estaba ahí …',
  'Tu auricular empieza a contarte chismes sobre la gente del colectivo …',
  'Una paloma se posa en tu hombro y te entrega un boleto de lotería …',
  'Estás tomando mate, y de la bombilla sale una voz muy molesta …',
  'El cajero del kiosco te entrega el vuelto en monedas que brillan demasiado …',
  'En la oficina, la impresora empieza a imprimir chistes sobre vos …',
  'Tu sombra se adelanta medio metro y empieza a bailar …',
  'Un repartidor toca tu timbre con un paquete, pero dice que es para “el futuro vos” …',
  'Te subís al taxi y el chofer te pregunta si traés el mapa del tesoro …',
  'Estás en el estadio y la pantalla gigante te enfoca, justo cuando …',
   'Vas caminando por una calle vacía, y escuchás un portón metálico abrirse detrás tuyo …',
  'Subís al colectivo y notás que todos los pasajeros llevan el mismo objeto en las manos …',
  'El teléfono suena en plena madrugada, atendés y nadie responde …',
  'Te llega un sobre sin remitente, con tu nombre escrito en tinta corrida …',
  'La puerta del ascensor se abre, pero el piso que ves no corresponde al edificio …',
  'En el parque, un niño deja caer un cuaderno con páginas llenas de símbolos …',
  'Estás en la estación de tren y el cartel anuncia un destino que no conocés …',
  'Se corta la luz en tu casa y, en la oscuridad, escuchás una respiración …',
  '<1> iba caminando por la calle de noche, pensando en sus cosas, cuando a lo lejos vio a <2> en ropa interior corriendo a toda velocidad …',
  'En la cancha, la hinchada empezó a cantar “olé, olé, olé, <1>” justo cuando <2> entraba con una pizza gigante …',
  '<1> entró al bondi y el chofer le dijo: “Saldo insuficiente, pero si me das un abrazo de <2> te dejo pasar” …',
  'Mientras <1> cebaba un mate, <2> apareció con una docena de churros y un megáfono anunciando la merienda …',
  'En el kiosco, <1> pidió un alfajor y el kiosquero le entregó un póster autografiado por <2> …',
  '<1> abrió la heladera y encontró a <2> tomando gaseosa directo de la botella …',
  'El semáforo estaba en rojo, <1> esperaba tranquilo, cuando <2> pasó en monociclo disfrazado de gaucho …',
  '<1> fue a cargar la SUBE, pero la máquina mostró la cara de <2> diciendo: “Saldo insuficiente, capo” …',
  'En la verdulería, <1> pidió bananas y el cajón se movió solo hasta mostrar a <2> escondido adentro …',
  '<1> entró al aula, y en el pizarrón gigante decía: “Clase dictada por <2> y <3>” …',
  'Durante el asado, <1> quiso dar vuelta la carne, pero <2> ya estaba sentado como juez con una planilla …',
  'En la fila del banco, el cajero automático empezó a imprimir selfies de <1> y <2> en la playa …',
  '<1> prendió la tele y había un noticiero transmitiendo a <2> bailando cumbia en vivo …',
  'En plena lluvia, <1> abrió el paraguas y adentro estaba <2> tomando mate …',
  'En el subte, <1> vio que la publicidad decía “Se busca a <2> para un casting de telenovela” …',
  '<1> iba en bici por la costanera cuando <2> lo pasó corriendo con una bandera argentina …',
  'En la plaza, las palomas rodearon a <1> mientras <2> les daba órdenes con un silbato …',
  'En el supermercado, <1> escaneó la tarjeta y en la pantalla apareció <2> cantando un tango …',
  'Durante la misa, <1> abrió el misal y encontró la foto de <2> vestido de arquero …',
  '<1> estaba en el colectivo cuando sonó el altavoz: “Próxima parada: casa de <2>” …',
  'En la oficina, la impresora empezó a sacar hojas con dibujos de <1> hechos por <2> …',
  'El semáforo cambió a azul y <1> escuchó la voz de <2> diciendo: “Dale, pasá” …',
  '<1> estaba en el cine, y el tráiler mostraba la historia de <2> como superhéroe …',
  'Mientras <1> esperaba el tren, un perro con chaleco inspector se acercó y le pidió boleto a <2> …',
  'En el boliche, las luces se apagaron y de repente apareció <1> en la cabina de DJ con <2> …',
  '<1> estaba en la panadería y el panadero ofrecía “la docena mágica hecha por <2>” …',
  'Cuando <1> abrió su celular, encontró un grupo nuevo llamado “Cumple de <2> y <3>” …',
  '<1> fue a pagar la cuenta del bar y en el ticket decía “Descuento especial para amigos de <2>” …',
  'En el partido de truco, <1> cantó envido y <2> salió de abajo de la mesa con las cartas ganadoras …',
  'En el colectivo, <1> escuchó la voz del GPS del chofer diciendo: “Atención, <2> está bajando en la próxima” …',
  'Durante el picnic, <1> abrió la canasta y adentro estaba <2> con una guitarra …',
  'En el hospital, el médico le entregó a <1> una receta firmada por <2> en crayones …',
  '<1> quiso prender la compu, pero en la pantalla aparecía la cara de <2> diciendo: “¿Arrancamos?” …',
  'En el shopping, <1> vio un maniquí que de repente se parecía mucho a <2> …',
  'Durante la tormenta, <1> escuchó un trueno que sonaba exactamente como la risa de <2> …',
  'En el casamiento, el cura preguntó si alguien se oponía y apareció <1> con <2> trayendo choripanes …',
  '<1> entró al baño del bar y en el espejo estaba escrita una declaración de amor firmada por <2> …',
  'Cuando <1> abrió la mochila, encontró una nota que decía: “Prestada por <2>, devolvela limpia” …',
  'En la parada de bondi, <1> se dio vuelta y vio que <2> manejaba el colectivo disfrazado …',
  'Durante el recreo, <1> escuchó a los árboles coreando el nombre de <2> …',
  'En el recital, el cantante frenó la canción para felicitar a <1> por venir con <2> …',
  'Mientras <1> tomaba mate, la bombilla empezó a cantar con la voz de <2> …',
  'En el gimnasio, <1> levantaba pesas, pero era <2> quien contaba las repeticiones …',
  '<1> fue a hacerse un tatuaje y el diseño ya estaba listo: la cara de <2> comiendo pizza …',
  'En la cancha de barrio, la pelota rodó sola hasta <1> mientras <2> gritaba gol …',
  'Cuando <1> quiso dormir, la almohada le susurró la receta de empanadas de <2> …',
  'En la parrilla, el parrillero gritó: “¡Se viene el asado de <1> y <2>!” …',
  '<1> bajó del taxi y el chofer le dio como vuelto una foto firmada por <2> …',
  'Durante el carnaval, <1> descubrió que la murga tenía como director a <2> …',
  '<1> entró a la facultad y en la cartelera gigante estaba el dibujo de <2> con bigotes falsos …',
  'En la esquina de su casa, <1> vio a <2> vendiendo entradas para un recital secreto de <3> …',
  'Abrís un libro usado y encontrás una fotografía pegada entre las páginas …',
  'Un desconocido en la calle te entrega una llave sin decir palabra …',
  'Estás en un café y tu nombre aparece escrito en la ventana empañada …',
  'La radio empieza a repetir una misma frase, una y otra vez …',
  'El semáforo cambia a un color que nunca habías visto …',
  'Caminás por el bosque y de repente los pájaros dejan de cantar …',
  'En el cielo aparece una luz estática que no se mueve ni desaparece …',
  'Recibís un mensaje de texto desde tu propio número de teléfono …',
  'Una puerta en tu casa que siempre estuvo cerrada aparece entreabierta …',
  'En el colectivo, la voz grabada anuncia una parada que no figura en el mapa …',
  'Estás a punto de dormir y alguien golpea suavemente la ventana …',
  'Una sombra en la pared se mueve en sentido contrario a tus gestos …',
  'El viento abre una hoja de tu cuaderno en blanco y aparecen palabras escritas …',
  'Un perfume desconocido invade la habitación sin que nadie haya entrado …',
  'En la esquina, un grupo de personas mira fijo hacia el cielo, sin hablar …',
  'Al sacar la basura, ves que una bolsa se mueve sola en la vereda …',
  'Mientras cocinás, la radio corta la música y menciona tu dirección exacta …',
  'El reloj de pared se detiene, y en ese mismo momento la lámpara parpadea …',
  'Vas a comprar facturas y la panadera te pregunta si querés llevar “el paquete misterioso de medialunas” …',
  'El bondi frena de golpe y el chofer te dice: “Acá bajan los campeones del mundo”, y en ese momento …',
  'Estás haciendo la fila del súper y el de adelante paga con figuritas del Mundial …',
  'Tu vecino te toca el timbre para pedirte azúcar, pero aparece con un mate y tres bizcochitos …',
  'El semáforo se pone en rojo y un tipo con camiseta de Boca te pregunta si tenés fuego …',
  'Ponés la pava en el fuego, y la pava te dice que no quiere laburar hoy …',
  'En la cancha, la hinchada empieza a cantar tu nombre aunque vos nunca jugaste …',
  'Estás en la verdulería y el cajón de papas se mueve solo mientras el verdulero silba …',
  'Un colectivo vacío frena justo al lado tuyo y el cartel de destino dice “Tu casa” …',
  'Vas al chino de la esquina y la máquina registradora te devuelve caramelos media hora …',
  'En el kiosco pedís un alfajor y el kiosquero te ofrece “el que cumple deseos” …',
  'Estás en la cola del banco y el de seguridad saca una guitarra y arranca un chamamé …',
  'La radio anuncia: “Atención, hoy se suspenden todos los lunes en Argentina”, y justo …',
  'Te sentás a tomar mate en la plaza y una paloma te pide un sorbo …',
  'Abrís la heladera y encontrás a tu gato durmiendo adentro con una docena de facturas …',
  'Estás en el subte y la voz del altavoz te saluda por tu nombre …',
  'La tele se prende sola y empieza a transmitir un partido que todavía no se jugó …',
  'En la esquina, un parrillero te ofrece un choripán “con final sorpresa” …',
  'El cajero automático no da billetes, te da entradas para un recital en Ferro …',
  'Mientras esperás el tren, aparece un perro con chaleco de inspector que pide tu boleto …',
  'Pedís delivery de empanadas y el repartidor te da un sobre cerrado además de la caja …',
  'En el laburo, la impresora empieza a escupir boletas electorales con tu nombre …',
  'Un colectivero te pregunta si vas a Once, pero no en bondi: en unicornio …',
  'Estás en la panadería y una docena de churros se autoproclama tu hinchada personal …',
  'El mozo de la pizzería te trae la grande de muzza y un contrato de jugador profesional …',
  'Vas a cargar la SUBE y el kiosquero te da un boleto de tren de 1942 …',
  'En la verdulería, una sandía rueda sola hacia vos como si quisiera hablarte …',
  'Caminás por Corrientes y un cartel luminoso empieza a mostrar tus tuits viejos …',
  'Tu celular vibra y te llega un audio de WhatsApp… grabado por vos en el futuro …',
  'En la cancha de barrio, la pelota se te acerca sola y dice: “Dale, pateame” …',
];