import { WordPair } from "./types";

export const WORD_SETS: WordPair[] = [
  { common: 'Playa', impostor: 'Desierto' },
  { common: 'Pizza', impostor: 'Empanada' },
  { common: 'Gato', impostor: 'Perro' },
  { common: 'Montaña', impostor: 'Volcán' },
  { common: 'Avión', impostor: 'Helicóptero' },
  { common: 'Mate', impostor: 'Té' },
  { common: 'Fútbol', impostor: 'Rugby' },
  { common: 'Asado', impostor: 'Parrillada' },
  { common: 'Colectivo', impostor: 'Tren' },
  { common: 'Bondi', impostor: 'Subte' },
  { common: 'Remera', impostor: 'Camisa' },
  { common: 'Ojota', impostor: 'Zapatilla' },
  { common: 'Birra', impostor: 'Vino' },
  { common: 'Fernet', impostor: 'Gancia' },
  { common: 'Choripán', impostor: 'Hamburguesa' },
  { common: 'Pancho', impostor: 'Hamburguesa' },
  { common: 'Picada', impostor: 'Asado' },
  { common: 'Helado', impostor: 'Postre' },
  { common: 'Chocolate', impostor: 'Caramelo' },
  { common: 'Manzana', impostor: 'Pera' },
  { common: 'Banana', impostor: 'Mandarina' },
  { common: 'Sandía', impostor: 'Melón' },
  { common: 'Durazno', impostor: 'Ciruela' },
  { common: 'Leche', impostor: 'Yogur' },
  { common: 'Agua', impostor: 'Jugo' },
  { common: 'Pan', impostor: 'Factura' },
  { common: 'Medialuna', impostor: 'Churro' },
  { common: 'Torta', impostor: 'Budín' },
  { common: 'Empanada', impostor: 'Tarta' },
  { common: 'Milanesa', impostor: 'Bife' },
  { common: 'Pollo', impostor: 'Carne' },
  { common: 'Pescado', impostor: 'Marisco' },
  { common: 'Queso', impostor: 'Jamón' },
  { common: 'Huevos', impostor: 'Queso' },
  { common: 'Papa', impostor: 'Batata' },
  { common: 'Zapallo', impostor: 'Calabaza' },
  { common: 'Choclo', impostor: 'Arveja' },
  { common: 'Arroz', impostor: 'Fideos' },
  { common: 'Salsa', impostor: 'Aderezo' },
  { common: 'Sal', impostor: 'Azúcar' },
  { common: 'Aceite', impostor: 'Vinagre' },
  { common: 'Sol', impostor: 'Luna' },
  { common: 'Día', impostor: 'Noche' },
  { common: 'Invierno', impostor: 'Verano' },
  { common: 'Frío', impostor: 'Calor' },
  { common: 'Campo', impostor: 'Ciudad' },
  { common: 'Río', impostor: 'Lago' },
  { common: 'Mar', impostor: 'Laguna' },
  { common: 'Sierra', impostor: 'Cordillera' },
  { common: 'Isla', impostor: 'Península' },
  { common: 'Calle', impostor: 'Avenida' },
  { common: 'Plaza', impostor: 'Parque' },
  { common: 'Casa', impostor: 'Departamento' },
  { common: 'Escuela', impostor: 'Universidad' },
  { common: 'Profesor', impostor: 'Alumno' },
  { common: 'Libro', impostor: 'Revista' },
  { common: 'Cuaderno', impostor: 'Agenda' },
  { common: 'Lápiz', impostor: 'Lapicera' },
  { common: 'Mochila', impostor: 'Bolso' },
  { common: 'Silla', impostor: 'Banco' },
  { common: 'Mesa', impostor: 'Escritorio' },
  { common: 'Puerta', impostor: 'Ventana' },
  { common: 'Llave', impostor: 'Candado' },
  { common: 'Televisor', impostor: 'Radio' },
  { common: 'Celular', impostor: 'Teléfono fijo' },
  { common: 'Computadora', impostor: 'Tablet' },
  { common: 'Teclado', impostor: 'Mouse' },
  { common: 'Pantalla', impostor: 'Proyector' },
  { common: 'Campera', impostor: 'Saco' },
  { common: 'Gorra', impostor: 'Sombrero' },
  { common: 'Bufanda', impostor: 'Guantes' },
  { common: 'Pantalón', impostor: 'Short' },
  { common: 'Vestido', impostor: 'Pollera' },
  { common: 'Ojota', impostor: 'Alpargata' },
  { common: 'Botín', impostor: 'Zapatilla' },
  { common: 'Auto', impostor: 'Moto' },
  { common: 'Camión', impostor: 'Colectivo' },
  { common: 'Bicicleta', impostor: 'Monopatín' },
  { common: 'Taxi', impostor: 'Remís' },
  { common: 'Semáforo', impostor: 'Cartel' },
  { common: 'Puente', impostor: 'Túnel' },
  { common: 'Peaje', impostor: 'Estacionamiento' },
  { common: 'Tren', impostor: 'Subte' },
  { common: 'Avión', impostor: 'Barco' },
  { common: 'Barco', impostor: 'Lancha' },
  { common: 'Velero', impostor: 'Crucero' },
  { common: 'Perro', impostor: 'Caniche' },
  { common: 'Gato', impostor: 'Tigre' },
  { common: 'Caballo', impostor: 'Burro' },
  { common: 'Vaca', impostor: 'Toro' },
  { common: 'Oveja', impostor: 'Cabra' },
  { common: 'Chancho', impostor: 'Jabalí' },
  { common: 'Gallina', impostor: 'Pato' },
  { common: 'Pato', impostor: 'Ganso' },
  { common: 'Ratón', impostor: 'Loro' },
  { common: 'Mosquito', impostor: 'Mosca' },
  { common: 'Araña', impostor: 'Hormiga' },
  { common: 'Hormiga', impostor: 'Avispa' },
  { common: 'León', impostor: 'Tigre' },
  { common: 'Elefante', impostor: 'Rinoceronte' },
  { common: 'Frío', impostor: 'Calor' },
  { common: 'Día', impostor: 'Noche' },
  { common: 'Alto', impostor: 'Bajo' },
  { common: 'Grande', impostor: 'Chico' },
  { common: 'Largo', impostor: 'Corto' },
  { common: 'Rápido', impostor: 'Lento' },
  { common: 'Cerca', impostor: 'Lejos' },
  { common: 'Viejo', impostor: 'Joven' },
  { common: 'Fuerte', impostor: 'Débil' },
  { common: 'Luz', impostor: 'Oscuridad' },
  { common: 'Blanco', impostor: 'Negro' },
  { common: 'Seco', impostor: 'Mojado' },
  { common: 'Vacío', impostor: 'Lleno' },
  { common: 'Pesado', impostor: 'Liviano' },
  { common: 'Rico', impostor: 'Pobre' },
  { common: 'Feliz', impostor: 'Triste' },
  { common: 'Risa', impostor: 'Llanto' },
  { common: 'Caro', impostor: 'Barato' },
  { common: 'Duro', impostor: 'Blandito' },
  { common: 'Claro', impostor: 'Oscuro' },
  { common: 'Nuevo', impostor: 'Viejo' },
  { common: 'Abierto', impostor: 'Cerrado' },
  { common: 'Encendido', impostor: 'Apagado' },
  { common: 'Primero', impostor: 'Último' },
  { common: 'Arriba', impostor: 'Abajo' },
  { common: 'Adelante', impostor: 'Atrás' },
  { common: 'Dentro', impostor: 'Fuera' },
  { common: 'Dulce', impostor: 'Amargo' },
  { common: 'Salado', impostor: 'Insípido' },
  { common: 'Caliente', impostor: 'Frío' },
  { common: 'Temprano', impostor: 'Tarde' },
  { common: 'Ancho', impostor: 'Angosto' },
  { common: 'Sano', impostor: 'Enfermo' },
  { common: 'Recto', impostor: 'Torcido' },
  { common: 'Claro', impostor: 'Nublado' },
  { common: 'Amigo', impostor: 'Enemigo' },
  { common: 'Subir', impostor: 'Bajar' },
  { common: 'Reír', impostor: 'Llorar' },
  { common: 'Dormir', impostor: 'Despertar' },
  { common: 'Encima', impostor: 'Debajo' },
  { common: 'Cielo', impostor: 'Infierno' },
  { common: 'Trabajo', impostor: 'Descanso' },
  { common: 'Entrar', impostor: 'Salir' },
  { common: 'Empezar', impostor: 'Terminar' },
  { common: 'Ganar', impostor: 'Perder' },
  { common: 'Comprar', impostor: 'Vender' },
  { common: 'Subida', impostor: 'Bajada' },
  { common: 'Tirar', impostor: 'Levantar' },
  { common: 'Llegar', impostor: 'Irse' },
  { common: 'Aparecer', impostor: 'Desaparecer' },
  { common: 'Recordar', impostor: 'Olvidar' },
  { common: 'Empujar', impostor: 'Tirar' },
  { common: 'Abrir', impostor: 'Cerrar' },
  { common: 'Rico', impostor: 'Feo' },
  { common: 'Mucho', impostor: 'Poco' },
  { common: 'Más', impostor: 'Menos' },
  { common: 'Arriba', impostor: 'Abajo' },
  { common: 'Derecha', impostor: 'Izquierda' },
  { common: 'Adentro', impostor: 'Afuera' },
  { common: 'Mayor', impostor: 'Menor' },
  { common: 'Subir', impostor: 'Caer' },
  { common: 'Encender', impostor: 'Apagar' },
  { common: 'Hombre', impostor: 'Mujer' },
  { common: 'Niño', impostor: 'Adulto' },
  { common: 'Calmo', impostor: 'Nervioso' },
  { common: 'Contento', impostor: 'Enojado' },
  { common: 'Listo', impostor: 'Tonto' },
  { common: 'Amor', impostor: 'Odio' },
  { common: 'Verdad', impostor: 'Mentira' },
  { common: 'Bien', impostor: 'Mal' },
  { common: 'Correcto', impostor: 'Incorrecto' },
  { common: 'Seguro', impostor: 'Inseguro' },
  { common: 'Fácil', impostor: 'Difícil' },
  { common: 'Positivo', impostor: 'Negativo' },
  { common: 'Igual', impostor: 'Diferente' },
  { common: 'Viejo', impostor: 'Nuevo' },
  { common: 'Tibio', impostor: 'Helado' },
  { common: 'Pesado', impostor: 'Liviano' },
  { common: 'Ancho', impostor: 'Fino' },
  { common: 'Bonito', impostor: 'Feo' },
  { common: 'Corto', impostor: 'Largo' },
  { common: 'Seco', impostor: 'Húmedo' },
  { common: 'Vacío', impostor: 'Completo' },
  { common: 'Subir', impostor: 'Bajar' },
  { common: 'Dar', impostor: 'Recibir' },
  { common: 'Encima', impostor: 'Debajo' },
  { common: 'Rápido', impostor: 'Lento' },
  { common: 'Cerca', impostor: 'Lejos' },
  { common: 'Claro', impostor: 'Oscuro' },
  { common: 'Risa', impostor: 'Llanto' },
  { common: 'Fuerte', impostor: 'Débil' },
  { common: 'Joven', impostor: 'Anciano' },
  { common: 'Temprano', impostor: 'Tarde' },
  { common: 'Duro', impostor: 'Blandito' },
  { common: 'Frente', impostor: 'Espalda' },
  { common: 'Entrada', impostor: 'Salida' },
  { common: 'Gordo', impostor: 'Flaco' },
  { common: 'Claro', impostor: 'Turbio' },

  // Fútbol argentino
  { common: 'Boca', impostor: 'River' },
  { common: 'Racing', impostor: 'Independiente' },
  { common: 'San Lorenzo', impostor: 'Huracán' },
  { common: 'Newell\'s', impostor: 'Rosario Central' },
  { common: 'Estudiantes', impostor: 'Gimnasia' },
  { common: 'Banfield', impostor: 'Lanús' },
  { common: 'Talleres', impostor: 'Belgrano' },
  { common: 'Colón', impostor: 'Unión' },
  { common: 'Platense', impostor: 'Argentinos Juniors' },
  { common: 'Atlético Tucumán', impostor: 'San Martín (Tucumán)' },

  // Fútbol internacional
  { common: 'Real Madrid', impostor: 'Barcelona' },
  { common: 'Inter', impostor: 'Milan' },
  { common: 'Manchester United', impostor: 'Manchester City' },
  { common: 'Liverpool', impostor: 'Everton' },
  { common: 'Bayern', impostor: 'Dortmund' },
  { common: 'Juventus', impostor: 'Inter' },
  { common: 'PSG', impostor: 'Marsella' },
  { common: 'Benfica', impostor: 'Porto' },

  // Celebridades argentinas
  { common: 'Maradona', impostor: 'Messi' },
  { common: 'Riquelme', impostor: 'Gallardo' },
  { common: 'Tévez', impostor: 'Agüero' },
  { common: 'Ginóbili', impostor: 'Scola' },
  { common: 'Ricardo Darín', impostor: 'Guillermo Francella' },
  { common: 'Susana Giménez', impostor: 'Mirtha Legrand' },
  { common: 'Charly García', impostor: 'Spinetta' },
  { common: 'Fito Páez', impostor: 'Andrés Calamaro' },
  { common: 'Tini', impostor: 'Lali' },
  { common: 'Abel Pintos', impostor: 'Luciano Pereyra' },

  // Marcas de autos
  { common: 'Toyota', impostor: 'Volkswagen' },
  { common: 'Ford', impostor: 'Chevrolet' },
  { common: 'Renault', impostor: 'Fiat' },
  { common: 'Peugeot', impostor: 'Citroën' },
  { common: 'BMW', impostor: 'Mercedes-Benz' },
  { common: 'Hyundai', impostor: 'Kia' },
  { common: 'Nissan', impostor: 'Honda' },
  { common: 'Jeep', impostor: 'Land Rover' },

  // Comida y bebida
  { common: 'Coca-Cola', impostor: 'Pepsi' },
  { common: 'McDonald\'s', impostor: 'Burger King' },
  { common: 'KFC', impostor: 'Popeyes' },
  { common: 'Starbucks', impostor: 'Dunkin' },
  { common: 'Quilmes', impostor: 'Brahma' },
  { common: 'Fernet Branca', impostor: '1882' },
  { common: 'Havanna', impostor: 'Cachafaz' },
  { common: 'Arcor', impostor: 'Bagley' },

  // Tech y apps
  { common: 'Apple', impostor: 'Samsung' },
  { common: 'Android', impostor: 'iOS' },
  { common: 'PlayStation', impostor: 'Xbox' },
  { common: 'WhatsApp', impostor: 'Telegram' },
  { common: 'Instagram', impostor: 'TikTok' },
  { common: 'YouTube', impostor: 'Twitch' },
];
